### ISSUE TITLE
Pressure = 10080000000000000, v.2.0.1

### ISSUE THREAD

**Issue by Fortunatto** [diyruz/AirSense#7]
Датчик BME280. Шлюз SLS. Показания  в строке давления "Pressure = 10080000000000000". На прошивке 2.0.0 этой ошибки не было.

**Comment by nurikk** [comment]
Maybe @xyzroe can help?

**Comment by xyzroe** [comment]
@Fortunatto прошивка с гита или сам собирал?

**Comment by xyzroe** [comment]
@nurikk your build DIYRuZ_AirSense_EndDevice_CC2591.hex uses 478,773 bytes.
The build from my fork uses 479,153 bytes.
Cloned the original repository just now, rebuilt it - uses 479,135 bytes.
The difference in the size of my builds is clear to me, but why is the difference between mine and your's build?
Some patches have not been applied?

**Comment by xyzroe** [comment]
@Fortunatto попробуй из архива билд использовать
[Archive.zip](https://github.com/diyruz/AirSense/files/5726492/Archive.zip)

@nurikk just checked my build from a local fork and own build from the master branch - the pressure displays correctly.
uploaded the build from git - the pressure does not scale correctly. I think some patched have not been applied.

**Comment by Fortunatto** [comment]
> @Fortunatto прошивка с гита или сам собирал?

С гита.

**Comment by xyzroe** [comment]
@Fortunatto 3.0.1 ставь

**Comment by Fortunatto** [comment]
> @Fortunatto 3.0.1 ставь, подключай внешний конвертер и будет ок
Поставил 3.0.1, подключил внешний конвертер. Возможно я "криворучка", но у меня исправилось давление, зато "сломалось" СО2: показывает 65535.

**Comment by xyzroe** [comment]
> Поставил 3.0.1, подключил внешний конвертер. Возможно я "криворучка", но у меня исправилось давление, зато "сломалось" СО2: показывает 65535.

@Fortunatto проверяйте сенсор со2. он 65535 может выдавать сразу после включение, после должно нормализоваться


> Не в тему давления, но заметил еще одну особенность: Прошил датчик в роутер. Подключаю через USB-стик Modkam V3 и zigbee2mqtt. Датчик СО2 подключается. Но пока он работает, никакие другие новые датчики спарить не получается. Если датчик СО2 отключить от питания, спаривание новых устройств проходит нормально.

видимо у вас в стике прошивка но которой роутеры не корректно отрабатывают спаривание. 
проблема к датчику СО2 отношения не имеет. в крайнем случае прошейте end конфигурацию.  

  


@nurikk I think you can close this issue.
